### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by lonix1** [soenneker/soenneker.cloudflare.turnstile.client#675]
Hi, thanks for making this nice library!

Updates are **extremely** frequent; often multiple times per day. Never seen anything like it! :smile: 

Is there a changelog?

**Comment by soenneker** [comment]
@lonix1 Thanks for your interest. 98% of the updates are simply updating underlying libraries, silently improving everything. Updates are best found via commits authored by me. I strive hard to keep the ecosystem non-breaking.. but don't feel the need to stay on latest.
